Squashed 'src/deps/src/lua-nginx-module/' changes from c47084b5d7..0e769b7643
0e769b7643 tests: 082-body-filter-2.t: skip this test if mockeagain is not loaded correctly. (#2275)
766b7a8add tests: use random ports instead of constant ports to prevent conflicts during testing. (#2274)
bf5d9d3b5c change: don't move the expired item to the lru queue head when lookup.
e8da8781c9 optimize: Make the use of NGX_PCRE2 clearer.
f249fa9b7e bugfix: fixed memory leak in the case of connection in dubious. (#2270)
8c7f9bf46a tests: t/129-ssl-socket.t: use the same IP to ensure that the ssl session can be reused. (#2267)
0d054a57f4 tests: t/128-duplex-tcp-socket: replacing constant port 7658 with a random port. (#2268)
ff96d75a49 tests: update openssl to 1.1.1w.
2d32c7c8d6 bumped version of lua-nginx-module to 10026.
75ab35d3c4 doc: add http2 and http3 limitation doc comment for ngx.req.socket API.
0c3675ff4d tests: adjust some test cases for HTTP3.
3a0b823d9f feature: make HTTP3 authority as http_host header.
577dfebba4 feature: add max_bytes argument for get_body_data() function.
339b08a4be doc: make some debug message and comments accurate.
187ad5c050 bugfix: failed to build when building without http2&http3 modules.
86bea01b24 changes: modify read body api limitation for HTTP/2 or HTTP/3 requests.
db80075e0a doc: more accurate error messages.
7661f9b48a tests: t/166-ssl-client-hello.t: fixed test plan.
87f41a9545 bugfix: fix some failed test case.
25c9643cf4 docs: remove duplicated sentence.
51984aea04 tests: check if the version number has been specified before downloading OpenSSL. (#2240)
5ae767d504 tests: build drizzle with python3.
488ba27110 bugfix: failed to compile with clang.
028852c156 enable http3 test.
c27df5c6ba tests: fixed test cases for http2 when running with TEST_NGINX_USE_HTTP2=1. (#62)
7c8a9d53e7 test3: more http3 tests fixes.
309edb6832 tests: fixed test for http3.
03ec7f1d71 bugfix: don't include pcre.h with PCRE2 used.
8e9c33a9ef tests: update t/cert/test.crl.
2448743b68 tests: update t/cert/test.crl.
f29e8487b2 doc: update TODO list since tcpsock:bind is already implemented.
cb83e33e26 feature: support pcre2
c89469e920 doc: update release date
e2d0505955 doc: revise the description regarding Nginx compatibility.
25b7959b29 bugfix: fixed compilation error: variable 'nelts' set but not used.
e69fd3de28 feature: upgrade nginx core to 1.25.1.
f39e7e50fe change: remove ngx.re from ngx.run_worker_thread.
caad24b355 doc: modified lua_ssl_certificate, lua_ssl_certificate_key and lua_ssl_trusted_certificate.
4ca27c48f5 Revert "feature: allow get empty key for ngx.req.get_uri()."
05da249316 feature: allow get empty key for ngx.req.get_uri().
b4c0450bbe feature: Support lua_ssl_certificate and lua_ssl_certificate_key.
f5c2d36101 Merge branch 'v0.10.25' into master.
bba3db08e7 bugfix: used after free when encountering invalid http IF-Match header.
592a91c1ab optimize: Optimized use of SSL contexts.
992cae739d doc: fixed typo.
28aced45f6 bugfix: ngx_http_lua_socket_tcp_bind is also allowed in ssl_session_fetch_by and ssl_client_hello_by.
64631297fb bugfix: ssl_client_hello_by_lua generating chunk cache key and chunk name
c9a0808c89 bugfix: when value type is SHDICT_TNUMBER, then it should get the number field instead of the bool field.
0c3853e124 bugfix: mixed recv api call causes unexpected result.
4bf1b0b8d7 change: lua-ssl-protocols: Disabled SSLv3 and enable TLSv1.3 by default.
c91fb13a8c doc: fix typo in the comment.
0090f3faf6 bugfix: disable http2 in body read due to http2 stream processing bug.
bf8c91d111 doc: fixed typo in error messages.
16de4bea62 bugfix: Fix handling of new list elements.
39941d4c9a tests: add two more test cases for body_filter_by_lua*.

git-subtree-dir: src/deps/src/lua-nginx-module
git-subtree-split: 0e769b76432df91e5f10aa56a56858e8a190faf7